### ISSUE TITLE
[Q] Ability to use multiple deployments under same resource

### ISSUE THREAD

**Issue by codylittle** [timoklimmer/powerproxy-aoai#57]
Hey,

Just want to start by saying great work! We've tried many of the aoai load balancing implementations, and this is by far the most robust & customizable one we've seend yet.
With the Assistants API being stateful on a per-resource basis, the ability to load balance between multiple deployments in the same resource would be beneficial.
ie, a single AOAI resource with 200PTU gpt-4 as deployment "gpt-4-1", then 280k TPM PAYG gpt-4 as "gpt-4-2".

I'll be looking at adding this as a plugin to just rewrite the URL, but wondering if there's another way of achieving this.

Regards,
Cody

**Comment by codylittle** [comment]
Hey @timoklimmer, in addition to the path variable being added to the routing slip. Having a plugin execution point after the checking for endpoint availability would be beneficial and streamline an implementation. Around [L225](https://github.com/timoklimmer/powerproxy-aoai/blob/main/app/powerproxy.py#L225) was my thinking.

**Comment by timoklimmer** [comment]
Hi @codylittle, I have just added the path to the routing slip in main. However, the more I think about it, the more I wonder if this would be better solved by generally load balancing across deployments instead of endpoints (if deployments are known). Currently, PowerProxy respects the retry-after-ms header and uses that info to skip an entire endpoint. If an endpoint has a deployment at capacity as well as others that are idle, the idle ones would not be used in that case, and a simple rewrite of the path cannot solve the problem because the entire endpoint would be skipped if there is a 429 from the endpoint.

We probably need to extend the configuration, add deployments there as well and - if available - use the deployment infos for load balancing instead of endpoints. I know that someone else wants to limit endpoints to certain deployments. So we would need deployment in the config anyway. Let me check details later today and come back.

Regarding the extra plugin execution point: I am happy to add another plugin execution endpoint but also need to be concious about latency. Which name do you think the on_... event should have? What would it be used for? If it's on spec, I would rather wait until we have a real requirement to avoid additional latency.

**Comment by codylittle** [comment]
Hey @timoklimmer, I was planning on utilizing multiple aoai.endpoints configurations with the same URL, example below

```yaml
aoai:
  endpoints:
    - name: PTU
      url: https://abcd.openai.azure.com/
      key: 123456
      non_streaming_fraction: 1

    - name: PAYG
      url: https://abcd.openai.azure.com/
      key: 123456
      non_streaming_fraction: 1
```

Then with a plugin configuration mapping endpoint names to deployment names to modify the path

```yaml
plugins:
  - name: DeploymentLB
    mapping:
      PTU: gpt-4-1
      PAYG: gpt-4-2
```

The ability to have deployment information nested within the configuration natively would be preferrable though.

In regards to the additional plugin execution, it would provide the ability to modify the routing slip based on which information relative to each endpoint. The choice of running after an endpoint had been chosen was to minimize unnecessary plugin calls on non-used/timed out endpoints. Side query - would there be additional latency even if no active plugins employ the specific plugin.

In terms of naming - I am horrible at naming, my suggestion would be `on_endpoint_chosen` or something more verbose `on_endpoint_chosen_for_attempt`

**Comment by codylittle** [comment]
In regards to deployments being available within the configuration, a means of mapping incoming model to configuration deployment would be good too. Would mean that requests for gpt-35-turbo could LB against different deployments to gpt-4. As well as ease the configuration overhead since config could be something like below:

```yaml
aoai:
    deployments:
        gpt-4: # the model name passed in the request to the proxy
            - deployment_name:
              url:
              key:
              non_streaming_fraction:

            - deployment_name:
              url:
              key:
              non_streaming_fraction:

        gpt-35-turbo:
            - deployment_name:
            ...  
```

**Comment by codylittle** [comment]
Hey @timoklimmer, apologies for the confusion, eventually I'll learn to read my own comments before posting.
When I referred to the model name being passed, I meant the deployment ID in the URL path.
Basically providing mapping from the deployment ID in path, to a different set/array of deployment IDs to LB against.

**Comment by krohm** [comment]
Hi @timoklimmer , we have often the problem, that not all regions are serving the same models, so maybe to overcome this issue, why not doing something like this:
```
- name: Some Endpoint
      url: https://___.openai.azure.com/
      # not required when Azure OpenAI's Azure AD/Entra ID authentication is used
      key: ___
      # fraction of non-streaming requests handled
      # 0   = endpoint will handle no non-streaming request
      # 0.7 = endpoint will handle 70% of the non-streaming requests it gets
      # 1   = endpoint will handle all non-streaming request it gets
      non_streaming_fraction: 1
      models: gpt-35-turbo,gpt-4

    - name: Another Endpoint
      url: https://___.openai.azure.com/
      # not required when Azure OpenAI's Azure AD/Entra ID authentication is used
      key: ___
      # fraction of non-streaming requests handled
      # 0   = endpoint will handle no non-streaming request
      # 0.7 = endpoint will handle 70% of the non-streaming requests it gets
      # 1   = endpoint will handle all non-streaming request it gets
      non_streaming_fraction: 1 
      models: gpt-35-turbo
```

**Comment by timoklimmer** [comment]
Hi @codylittle, @krohm, @sterankin: thanks (again) for all your good feedback. I have thought about it, and my idea would be to change the config options to something like this.

```yaml
aoai:
  endpoints:
    - name: Some Endpoint
      url: https://___.openai.azure.com/
      # optional. stays as is of today = depending on chance, we either try to handle the incoming request on this
      # endpoint, or directly pass it on to the next endpoint
      non_streaming_fraction: 1
      # new and optional. if deployments are configured, only the listed deployments are allowed. without deployments
      # item, behaviour stays as is today.
      deployments:
        # - deployment name is virtual, and PowerProxy would try deployments from the available standins, or pass on to next endpoint
        - name: gpt-35-turbo
          standins:
            - name: gpt-35-turbo-1
              # optional, similar to other non_stream_fraction's, 1 if not specified
              non_streaming_fraction: 0.5
            - name: gpt-35-turbo-2
            - name: gpt-35-turbo-3
        - name: gpt-4-turbo
          standins:
            - name: gpt-4-turbo-1
            - name: gpt-4-turbo-2
            - name: gpt-4-turbo-3

    - name: Another Endpoint
    ...
```

Regarding the feature to limit access for clients to specific endpoints/deployments, I think it's better to have this handled through an update of the LimitUsage plugin, and specifying access in the config where individual clients are defined. That however should be done once we have the deployment changes (as proposed above).

Any thoughts? Would the proposed config change work for you?

**Comment by codylittle** [comment]
Hey @timoklimmer, just want to confirm, using the above configuration: If I sent a request to gpt-35-turbo, it would first hit "Some Endpoint" and attempt gpt-35-turbo-1, then once a rate limit is reached, move onto gpt-35-turbo-2, or move onto "Another Endpoint"?

Other than just confirming that, LGTM.

**Comment by timoklimmer** [comment]
Hi @codylittle, your understanding is right. It would first try gpt-35-turbo-1, then gpt-35-turbo-2 etc., and if there no suitable deployment available at the endpoint, it would try the next endpoint and do the same on the next endpoint = if suitable deployments are defined, iterate those, and if no deployments are defined, just send the request to the endpoint.

**Comment by timoklimmer** [comment]
Hi @codylittle, @krohm, @sterankin -- good news 🎉. I have added a virtual deployments feature yesterday, which finally gives the option to load balance across deployments. The following config snippet speaks more than 1,000 words (hopefully 😁)

```yaml
aoai:
  endpoints:
    - name: Some Endpoint
      url: https://___.openai.azure.com/
      key: ___

      # optional
      virtual_deployments:
        - name: gpt-35-turbo  # can be any arbitrary name, deployment name to be used in requests to PowerProxy
          standins:
            - name: gpt-35-turbo-ptu  # name of existing deployment
              #optional: non_streaming_fraction: 0.8
            - name: gpt-35-turbo-paygo
        - name: gpt-4-turbo
          standins:
            - name: gpt-4-turbo-ptu
              #optional: non_streaming_fraction: 0.8
            - name: gpt-4-turbo-paygo
```

Now if you have certain deployments only available in certain regions, add multiple endpoints in the config (for example being in different regions) and add whatever virtual deployments you want to use from those respective endpoints. That way, you can have multiple endpoints, whereby not all of the endpoints needs to have all deployments/models available. Only thing to watch out are endpoints in the config without virtual deployments configured. If an endpoint does not have virtual deployments configured, it will be sent any request, no matter which deployment is requested.

Besides, I have added a new plugin named "AllowDeployments", which can be used to restrict access to certain deployments. If enabled, clients can only use the virtual deployments specified for them.

```yaml
clients:
  - name: Team 1
    description: An example team named 'Team 1'.
    key: ___
    deployments_allowed: gpt-35-turbo, gpt-4-turbo
```

I think/hope that addresses your feedback. If not, let me know. I will do some more testing and still need to update the documentation, but once that is done, I will release a new version soon. Enjoy 🙂
